management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0 

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9002/eureka/
  instance:
    ip-address: true

logging:
  pattern:
    level: '%5p [%X{traceId:-},%X{spanId:-},${spring.application.name:}]'      
